### ISSUE TITLE
Basic Static Website Pages

### ISSUE THREAD

**Issue by tiffanyadrienne** [emmagogogo/cs-160-group-2#12]
- Home Page
- Navigation bar
- Profile Page
- Jobs Page
- Network Page
- Posts Page
- Dashboard Page

**Comment by temuudei** [comment]
I will be working on implementing the search location bars.

**Comment by tiffanyadrienne** [comment]
Cases: 
1. runs on localhost
2. displays all pages 
3. all page text appears correctly
4. buttons work correctly

**Comment by temuudei** [comment]
Case:
Search bar correctly shows on the main page
