### ISSUE TITLE
Learn JS

### ISSUE THREAD

**Issue by emmagogogo** [emmagogogo/cs-160-group-2#13]

**Comment by emmagogogo** [comment]
callback function

**Comment by Saif-El-Eslam** [comment]
the DOM 
selecting HTML elements with JS
changing styles of HTML elements with JS
changing the HTML element text and attributes 
adding event listeners

**Comment by temuudei** [comment]
Things I learned:
Data types,
variables,
functions,
DOM manipulation,
event listeners to a button,
playing sounds
