### ISSUE TITLE
Learn HTML CSS

### ISSUE THREAD

**Issue by temuudei** [emmagogogo/cs-160-group-2#16]

**Comment by Saif-El-Eslam** [comment]
create static websites and style them

**Comment by tiffanyadrienne** [comment]
(CSS)
Goal: Stylize our website with CSS

Focus:
- syntax, selectors, classes, ids, HTML divs

**Comment by temuudei** [comment]
HTML:
Lists, elements, tables, forms, classes
CSS:
Inline, external, internal, selectors, IDS
