### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by tiffanyadrienne** [emmagogogo/cs-160-group-2#21]
Pages of wireframe:

home page
job page
message page
sign in / sign up
profile page

**Comment by tiffanyadrienne** [comment]
Pages of wireframe: 
- home page
- job page
- message page
- sign in / sign up
- profile page

**Comment by tiffanyadrienne** [comment]
Test Case:
1. every page has a rough outline of elements

**Comment by temuudei** [comment]
Created the message page where employees and employers would be able to communicate with each other.
