### ISSUE TITLE
Backend: Job Information CRUD

### ISSUE THREAD

**Issue by zychin2000** [emmagogogo/cs-160-group-2#30]
GET /jobs/:id
Return all job details regarding the job

POST /jobs/
Publish a job for the public. Only available for recruiters.

DELETE /jobs/:id
Delete a job listing

**Comment by emmagogogo** [comment]
1. created job schema and model

**Comment by zychin2000** [comment]
finished in commit c27d465983d8f7108df6b4aa4040a5e24235f919
