### ISSUE TITLE
BackEnd: Authenticiton and security

### ISSUE THREAD

**Issue by temuudei** [emmagogogo/cs-160-group-2#7]
1. Login/register flow. Registering a user inserts a user in the database. When logging in, system checks the password of the user.

2. User session

**Comment by emmagogogo** [comment]
Create User Schema and model and set data validations.
connect the database to the Node.js

**Comment by zychin2000** [comment]
Test Cases:
1. Register page is working, new user appears in database.
2. Login page adds user registered in register
